const Menu =[
    {
    id: 1,
    image: "images/T-shirt1.jpg",
    name: "H&M T-shirt",
    category: "Clothes",
    price: "975",
    quantity:1,
    availableQuantity : 15,
    description:
      "Regular Fit \n 100% cotton Typographic Print Crew-Neck- T-shirt",
  },
  {
    id: 2,
    image: "images/T-shirt2.jpg",
    name: "H&M T-shirt",
    category: "Clothes",
    price: "585",
    quantity:1,
    availableQuantity : 15,
    description:
      "Regular Fit \n 100% cotton Typographic Print Crew-Neck- T-shirt",
  },
  {
    id: 3,
    image: "images/Jeans1.jpg",
    name: "Jack & Jones Jeans ",
    category: "Clothes",
    price: "1,374",
    quantity:1,
    availableQuantity : 15,
    description:
      "Regular Fit \n 100% cotton High-Rise Slim Fit Ankle-Length Jeans",
  },
  {
    id: 4,
    image: "images/Jeans2.jpg",
    name: "Jack & Jones Jeans",
    category: "Clothes",
    price: "999",
    quantity:1,
    availableQuantity : 15,
    description:
      "Regular Fit \n 100% cotton High-Rise Slim Fit Ankle-Length Jeans",
  },
  {
    id: 5,
    image: "images/Jeans3.jpg",
    name: "Jack & Jones Jeans ",
    category: "Clothes",
    price: "1,074",
    quantity:1,
    availableQuantity : 15,
    description:
      "Regular Fit \n 100% cotton High-Rise Slim Fit Ankle-Length Jeans",
  },
  {
    id: 6,
    image: "images/T-shirt3.jpg",
    name: "H&M T-shirt",
    category: "Clothes",
    price: "180",
    quantity:1,
    availableQuantity : 15,
    description:
      "Regular Fit \n 100% cotton Typographic Print Crew-Neck- T-shirt",
  },
  {
    id: 7,
    image: "images/Phone1.jpg",
    name: "OnePlusNord 2T 5G",
    category: "Accessories",
    price: "28,999",
    quantity:1,
    availableQuantity : 15,
    description:
      "Jade fog,8GB RAM,128GB Storage",
  },
  {
    id: 8,
    image: "../images/Phone2.jpg",
    name: "Samsung Galaxy M11 ",
    category: "Accessories",
    price: "11,999",
    quantity:1,
    availableQuantity : 15,
    description:
      "Jade fog,8GB RAM,128GB Storage",
  },
  {
    id: 9,
    image: "../images/Phone3.jpg",
    name: "Samsung Galaxy M21",
    category: "Accessories",
    price: "14,999",
    quantity:1,
    availableQuantity : 15,
    description:
      "Jade fog,8GB RAM,128GB Storage",
  },
  {
    id: 10,
    image: "../images/Phone4.jpg",
    name: "Samsung Galaxy F13",
    category: "Accessories",
    price: "12,999",
    quantity:1,
    availableQuantity : 15,
    description:
      "Jade fog,8GB RAM,128GB Storage",
  },
  {
    id: 11,
    image: "../images/Phone5.jpg",
    name: "Samsung Galaxy F23",
    category: "Accessories",
    price: "14,999",
    quantity:1,
    availableQuantity : 15,
    description:
      "Jade fog,8GB RAM,128GB Storage",
  },
  {
    id: 12,
    image: "../images/Phone6.jpg",
    name: "Samsung Galaxy M32",
    category: "Accessories",
    price: "14,999",
    quantity:1,
    availableQuantity : 15,
    description:
      "Jade fog,8GB RAM,128GB Storage",
  },
  {
    id: 13,
    image: "../images/Phone7.jpg",
    name: "Samsung Galaxy F22",
    category: "Accessories",
    price: "11,499",
    quantity:1,
    availableQuantity : 15,
    description:
      "Jade fog,8GB RAM,128GB Storage",
  },
  {
    id: 15,
    image: "../images/Onion.jpg",
    name: "Fresh Onion ",
    category: "Grocery",
    price: "25",
    quantity:1,
    availableQuantity : 15,
    description:
      "1 Kg sack",
  },
  {
    id: 16,
    image: "../images/Bhendi.jpg",
    name: "Fresh Bhendi",
    category: "Grocery",
    price: "32",
    quantity:1,
    availableQuantity : 15,
    description:
      "500 gm ",
  },
  {
    id: 17,
    image: "../images/Ginger.jpg",
    name: "Fresh Ginger",
    category: "Grocery",
    price: "9",
    quantity:1,
    availableQuantity : 15,
    description:
      "100 gm ",
  },
  {
    id: 18,
    image: "../images/Coriander.jpg",
    name: "Fresh Coriander",
    category: "Grocery",
    price: "14",
    quantity:1,
    availableQuantity : 15,
    description:
      "100 gm ",
  },
  {
    id: 19,
    image: "../images/Bottle Gourd-1.jpg",
    name: "Fresh Bottle Gourd-1",
    category: "Grocery",
    price: "32",
    quantity:1,
    availableQuantity : 15,
    description:
      "1 piece",
  },
  {
    id: 20,
    image: "../images/Pan.jpg",
    name: "Prestige Aluminium Pan",
    category: "Home & Kitchen Stuffs",
    price: "980",
    quantity:1,
    availableQuantity : 15,
    description:
      "1 piece",
  },
  {
    id: 21,
    image: "../images/Toaster.jpg",
    name: "Toaster",
    category: "Home & Kitchen Stuffs",
    price: "499",
    quantity:1,
    availableQuantity : 15,
    description:
      "1 piece",
  },
  {
    id: 22,
    image: "../images/Blender.jpg",
    name: "blender",
    category: "Home & Kitchen Stuffs",
    price: "599",
    quantity:1,
    availableQuantity : 15,
    description:
      "1 piece",
  },
  {
    id: 23,
    image: "../images/Garlic-press.jpg",
    name: "Garlic Press",
    category: "Home & Kitchen Stuffs",
    price: "399",
    quantity:1,
    availableQuantity : 15,
    description:
      "1 piece",
  },
  {
    id: 24,
    image: "../images/Kettle.jpg",
    name: "Kettle",
    category: "Home & Kitchen Stuffs",
    price: "499",
    quantity:1,
    availableQuantity : 15,
    description:
      "1 piece",
  },
  {
    id: 25,
    image: "../images/Cake-pan.jpg",
    name: "cake pan",
    category: "Home & Kitchen Stuffs",
    price: "14",
    quantity:1,
    availableQuantity : 15,
    description:
      "100 gm ",
  },
  {
    id: 26,
    image: "../images/Tomatoes.jpg",
    name: "Fresh tomato",
    category: "Grocery",
    price: "14",
    quantity:1,
    availableQuantity : 15,
    description:
      "100 gm ",
  },
 ]
export default Menu;